export const COLORS = {
  primary: "#173FD4",
  borderColor: "#ECECEC",
  backgroundColor: "#F7F5F9",
  disabledColor: "#C4C4C4",
  purpleOverLay: '#B5ACFE',
  grayBorder: '#37474F',

  lightPrimary: "#B8C3D5",
  primaryContrast: "#EFFFF2",
  secondary: "#FF7D1F",
  error: "#FF735E",
  info: "#7484FC",
  success: "#81E542",
  warning: "#FCDA00",

  headingColor: "#1F2937",
  black: "#000000",
  white: "#FFFFFF",

  tint: "#EFFFF2",
  tint02: "#FBFCFE",

  text01: "#1A1D1B",
  text02: "#464D55",
  text03: "#1a1d1b66",
  text04: "#1a1d1b33",
  text05: "#1a1d1b1a"
}

export const IMGS = {

  weekTitleBg: '/assets/images/week-title-bg.png',
  avatarMan: '/assets/images/avatar/avatar-man.png',
  avatarWoman: '/assets/images/avatar/avatar2.png',
  avatarThumb: '/assets/images/thumb.png',
  avatarDoctor1: '/assets/images/avatar/avatar-doctor1.png',
  avatarDoctor2: '/assets/images/avatar/avatar-doctor2.png',
  avatarDoctor3: '/assets/images/avatar/avatar-doctor3.png',

  // fake
  ads1: '/assets/images/ads-1.png',
  adsSlide1: '/assets/images/ads-1-slide1.png',
  adsSlide2: '/assets/images/ads-1-slide2.png',
  adsSlide3: '/assets/images/ads-1-slide3.png',
  adsSlide4: '/assets/images/ads-1-slide4.png',
  cardImage1: '/assets/images/card-image1.png',
  profileBack: '/assets/images/profile-back.png',
  poemImg: '/assets/images/POEM.png',
  slide1: '/assets/images/slide1.png',
  slide2: '/assets/images/slide2.png',
  slide3: '/assets/images/slide3.png',
  slide4: '/assets/images/slide4.png',
  slide5: '/assets/images/slide5.png',
  loginCorner: '/assets/images/login-corner.png',
  loginBG: '/assets/images/login-bg.png',
  uploadBG: '/assets/images/upload-bg.png',
  topEllipseBG: '/assets/images/top_ellipse.png',
  leftEllipseBG: '/assets/images/left_ellipse.png',
  topEllipseBGSVG: '/assets/images/svg/top_ellipse.svg',
  leftEllipseBGSVG: '/assets/images/svg/left_ellipse.svg',
  signupBG: '/assets/images/signup_banner.png',
  signinBG: '/assets/images/signin_banner.png',
  verifyPhoneBG: '/assets/images/verifyphone_banner.png',
  agreementBG: '/assets/images/agreement_banner.png',
  failureBackground: '/assets/temp/fail.png',
  missedAptIcon: '/assets/missed-rmbg.png',
}

export const ICONS = {
  fakeLogo: '/assets/icons/fake-logo.png',
  backArrow: '/assets/icons/arrow-left.png',
  bell: '/assets/icons/bell.png',
  magnifyingGlass: '/assets/icons/magnifying-glass.png',
  dropdownIcon: '/assets/icons/dropdown-icon.png',
  dropdownIconGray: '/assets/icons/dropdown-icon-gray.png',
  mapMarker: '/assets/icons/map-marker.png',
  camera: '/assets/icons/camera.png',
  linePhone: '/assets/icons/line-phone.png',
  mobilePhone: '/assets/icons/mobile-phone.png',
  heartFavorit: '/assets/icons/heart-favorit.png',
  heartFilled: '/assets/icons/heart-filled.png',
  starFilled: '/assets/icons/star-filled.png',
  starEmpty: '/assets/icons/star-empty.png',
  webfy: '/assets/icons/webfy.png',
  markerBlue: '/assets/icons/marker-blue.png',
  settingIcon: '/assets/icons/setting-icon.png',
  calendar: '/assets/icons/calendar.png',
  arrowLeft: '/assets/icons/arrow-left.png',
  arrowLeftBlue: '/assets/icons/arrow-left-blue.png',
  arrowRight: '/assets/icons/arrow-right.png',
  arrowRightBlue: '/assets/icons/arrow-right-blue.png',
  arrowDownCircle: '/assets/icons/arrow-down-circle.png',
  arrowBackCircle: '/assets/icons/arrow-back-circle.png',
  arrowNextCircle: '/assets/icons/arrow-next-circle.png',
  orangeStar: '/assets/icons/orange-star.png',
  squareAdd: '/assets/icons/bx_bx-message-square-add.png',
  warning: '/assets/icons/warning.png',
  copyLink: '/assets/icons/copy-link.png',
  dashedLine: '/assets/icons/dashed-line.png',
  redClose: '/assets/icons/red-close.png',
  editUnderline: '/assets/icons/edit-underline.png',
  iconGoogle: '/assets/icons/icon-google.png',
  iconApple: '/assets/icons/icon-apple.png',
  iconWindows: '/assets/icons/icon-windows.png',
  iconFacebook: '/assets/icons/icon-facebook.png',
  eyeOn: '/assets/icons/eye-on.png',
  eyeOff: '/assets/icons/eye-off.png',
  radioOn: '/assets/icons/radio-on.png',
  radioOff: '/assets/icons/radio-off.png',
  checkOn: '/assets/icons/check-on.png',
  checkOff: '/assets/icons/check-off.png',
  checkOnDisabled: '/assets/icons/check-on-disabled.png',
  cardIcon: '/assets/icons/card-icon.png',
  tripleArrow: '/assets/icons/triple-arrow.png',
  edit: '/assets/icons/edit.png',
  forward: '/assets/icons/forward.png',
  bell2: '/assets/icons/bell2.png',
  reply: '/assets/icons/reply.png',
  mic: '/assets/icons/mic.png',
  alertRing: '/assets/icons/alert-ring.png',
  alertVibration: '/assets/icons/alert-vibration.png',
  alertNotification: '/assets/icons/alert-notification.png',
  tooth: '/assets/icons/tooth.png',
  glasses: '/assets/icons/glasses.png',
  jpeg: '/assets/icons/jpeg-icon.png',
  pdf: '/assets/icons/pdf-icon.png',
  aptCancelled: '/assets/icons/apt-cancelled.png',
  aptRescheduled: '/assets/icons/apt-rescheduled.png',
  dollar: '/assets/icons/dollar.png',
  high_important: '/assets/icons/high-important.png',
  mention: '/assets/icons/mention.png',
  message: '/assets/icons/message.png',
  transcription: '/assets/icons/transcription.png',
  canceledBadge: '/assets/icons/canceled-badge.png',
  rescheduledBadge: '/assets/icons/rescheduled-badge.png',
  myNotes: '/assets/icons/my-notes.png',
  highImportantMark: '/assets/icons/high-important-mark.png',
  arrowDown: '/assets/icons/arrow-down.png',
  pauseIcon: '/assets/icons/pause-icon.png',
  pwdHelp: '/assets/images/help_ico.png'
}

export const DV_SIZE = {
  mobileS: '320px',
  mobileM: '375px',
  mobileL: '425px',
  tablet: '768px',
  laptop: '1024px',
  laptopL: '1440px',
  desktop: '2560px'
}

